### ISSUE TITLE
Good job! 

### ISSUE THREAD

**Issue by KyleBing** [maan-patel/advanced-calculator#1]
I just wanna say: good job!  Very useful lib.
I have written a simple calculator with this as its core, and it is very efficient.
Thank you for your contribution.

> [https://kylebing.cn/tools/calculator/](https://kylebing.cn/tools/calculator/)

![](https://user-images.githubusercontent.com/12215982/161226848-668b1667-0121-4db5-9f6a-333a1a70cc15.png)

**Comment by maan-patel** [comment]
Glad you liked the library and found it efficient! 
Feel free to email me any feedback at ma23pate@gmail.com.

Thanks for making my day. 😄
